# Chapter 8 - Error Handling

‚ö†Ô∏è THIS CHAPTER IS WORTH RE-READING and REVIEWING

- How do errors fit within the broader architecture of our application?
- What does a good _error_ look like?
- Who are errors for?
- Should we use a library?
  - Which one?

## Internal Errors

- The function caller most likely wants to be informed **if** a failure occurs
  - So it can _react accordingly_ i.e.: retry or propagate the failure upstream with `?`
- Rust leverages the type system to communicate whether an operation succeeded or failed via:

```rust
pub enum Result<Success, Error> {
  Ok(Success),
  Err(Error)
}
```

> üëÜ The caller is then forced by the compiler to express how they plan to handle both scenarios: _success_ ad _failure_

If the goal was **only** to communicate to the caller that an error occurred:

```rust
pub enum ResultSignal<Success> {
  Ok(Success),
  Err
}
```

Errors serve two main purposes:

- Control flow (i.e. determine what to do next)
- Reporting (e.g. investigate, after the fact, what went wrong)

Distinguishing errors based on their location:

- Internal (i.e. function calling another function within our application)
- At the edge (i.e. an API request that we failed to fulfill)

Control flow is scripted:

- All information required to take a decision on what to do next must be accessible to a **machine**
- We use types (e.g. enum variants), methods and fields for internal errors.
- We rely on status codes for errors at the edge.
- Error reports are primarily consumed by **humans**.

| ----------------- | **Internal**           | **At the edge** |
| ----------------- | ---------------------- | --------------- |
| **Control Flow**  | Types, methods, fields | Status codes    |
| **Reporting**     | Logs/traces            | Response body   |

- Keep in mind that the line between a _user_ and an _operator_ can be blurry
  - e.g. a user might have access to the source code or they might be running the software on their own hardware

---

> `actix_web::Error` is used to carry errors from std::error through `actix_web` in a convenient way.

- `actix_web::Error` can be created by converting errors with into().

Rust orphan rule:

> it is forbidden to implement a foreign trait for a foreign type (where foreign stands for "from another crate")

- This restriction is meant to preserve coherence

## Trait Objects

- `dyn Error` a trait object that implements the `Error` trait
- Trait Objects like generic type parameters are a way to achieve polymorphism in Rust
  - i.e. invoke different implementations of the same interface
- Generic types are resolved at compile-time (static dispatch) whereas trait objects incurs a runtime cost (dynamic dispatch)

> The Error trait provides a `downcast_ref` which can be used to obtain a concrete type back from `dyn Error`,
> assuming you know what type to downcast to. There are legitimate use cases for down-casting,
> **but if you find yourself reaching for it too often** it might be a sign that something is not quite right in your design/error handling strategy.

## Removing Boilerplate With `thiserror`

`thiserror::Error` is a procedural macro used:

```rust
#[derive(thiserror::Error)]
pub enum SubscribeError {
    #[error("{0}")]
    ValidationError(String),
    #[error("Failed to acquire a Postgres connection form the pool")]
    PoolError(sqlx::Error),
    #[error("Failed to insert new subscriber in the database")]
    InsertSubscriberError(sqlx::Error),
    #[error("Failed to store the confirmation token for a new subscriber")]
    StoreTokenError(StoreTokenError),
    #[error("Failed to commit SQL transaction to store a new subscriber")]
    TransactionCommitError(sqlx::Error),
    #[error("Failed to send a confirmation email")]
    SendEmailError(reqwest::Error),
}
```

The macro receives at compile-time the definition of `SubscribeError` as input and return another stream of tokens as output

- It generates new Rust code which is then compiled into the final binary

`#[derive(thiserror::Error)]` provides:

- `#[error(/* */)]` defines the `Display` representation of the enum variant it's applied to
- `#[source]` is used to denote that should be returned as root cause in `Error::source`
- `#[from]` automatically derives an implementation of `From` for the type it has been applied to into the top-level error

`String` does not implement the `Error` trait so `#[from]` and `#[source]` cannot be used

## Avoid "Ball of Mud" Error Enums

```rust
#[derive(thiserror::Error)]
pub enum SubscribeError {
    #[error("{0}")]
    ValidationError(String),
    #[error(transparent)]
    UnexpectedError(#[from] Box<dyn std::error::Error>),
}
```

`transparent` delegates both `Display`'s and `source`'s implementation to the type wrapped by `UnexpectedError`

- We are wrapping `dyn std::error::Error` into a `Box` because the size of trait objects is not known at compile-time:
  - Trait objects can be used to store different types which will most likely have a different layout in memory
  - In Rust lingo they are **unsized**
  - They do not implement the `Sized` marker trait
- A `Box` stores the trait object itself on the heap, while we store the pointer to its heap location in `Subscribe::Error::UnexpectedError`
  - The pointer itself has a known size at compile-time

## Using `anyhow` As Opaque Error Type

[dtolnay](https://github.com/dtolnay/) is the same author for:

- [thiserror](https://github.com/dtolnay/thiserror) _derive(Error) for struct and enum error types_
- [anyhow](https://github.com/dtolnay/anyhow) _Flexible concrete Error type built on `std::error::Error`_
- [serde](https://github.com/dtolnay/serde) _Serialization framework for Rust_
- [syn](https://github.com/dtolnay/syn) _Parser for Rust source code_
- [quote](https://github.com/dtolnay/quote) _Rust quasi-quoting_
- etc...

> `anyhow::Error` is a wrapper around a dynamic error type.
> `anyhow::Error` works a lot like `Box<dyn std::error::Error>`,
> but with these differences:
>
> - `anyhow::Error` requires that the error is `Send`, `Sync`, and `'static`.
> - `anyhow::Error` guarantees that a backtrace is available, even if the underlying error type does not provide one.
> - `anyhow::Error` is represented as a narrow pointer - exactly one word in size instead of two.

```rust
pub async fn subscribe(
    form: web::Form<FormData>,
    pool: web::Data<PgPool>,
    email_client: web::Data<EmailClient>,
    base_url: web::Data<ApplicationBaseUrl>,
) -> Result<HttpResponse, SubscribeError> {
    let new_subscriber = form.0
      .try_into()
      .map_err(SubscribeError::ValidationError)?;

    let subscription_token = generate_subscription_token();

    let mut transaction = pool
        .begin()
        .await
        .context("Failed to acquire a Postgres connection from the pool")?;

    let subscriber_id = insert_subscriber(&mut transaction, &new_subscriber)
        .await
        .context("Failed to inesrt new subscriber in the database")?;

    store_token(&mut transaction, subscriber_id, &subscription_token)
        .await
        .context("Failed to store the confirmation token for a new subscriber")?;

    transaction
        .commit()
        .await
        .context("Failed to commit SQL transaction to store a new subscriber")?;

    send_confirmation_email(
        &email_client,
        new_subscriber,
        &base_url.0,
        &subscription_token,
    )
    .await
    .context("Failed to send a confirmation email")?;

    Ok(HttpResponse::Ok().finish())
}
```

The `context` method is performing double duties:

- It converts the error returned by our methods into an `anyhow::Error`
- It enriches it with additional context around the intentions of the caller.

## `anyhow` Or `thiserror`?

Rust myth:

> `anyhow` is for applications, `thiserror` is for libraries.

Do you expect the caller to behave differently based on the failure mode they encounter?

- Use an error enumeration, empower them to match on the different variants
- Bring in `thiserror` to write less boilerplate

Do you expect the caller to just give up when a failure occurs?

Is their main concern reporting the error to an operator or a user?

- Use an opaque error, do not give the caller _programmatic_ access to the error inner details
- Use `anyhow` or `eyre` if you find their API convenient

The misunderstanding arises from the observation that most Rust libraries return an error enum instead of `Box<dyn std:error::Error>` (e.g. `sqlx::Error`)

- Library authors **cannot** (_or do not want to_) make assumptions on the intent of their users.

- enums give users more control if they need it
- Freedom comes at a price of complexity; users need to sift through 10+ variants

## Who should log errors?

> errors should be logged when they are handled

- If your function is propagating the error upstream (e.g. using the `?` operator), it should **not** log the error.
- If the error is propagated all the way up to the request handler, delegate logging to a dedicated middleware (e.g. `tracing_actix_web::TracingLogger`)

## üì¶ Used

- [thiserror](https://crates.io/crates/thiserror)
- [anyhow](https://crates.io/crates/anyhow)

## References

- [Error handling Isn't All about Errors](https://www.youtube.com/watch?v=rAF8mLI0naQ)
- [Rust's orphan rule](https://doc.rust-lang.org/book/ch10-02-traits.html#implementing-a-trait-on-a-type)
- [Rust Error Handling Working Group](https://blog.rust-lang.org/inside-rust/2020/11/23/What-the-error-handling-project-group-is-working-on.html)
- [Using Trait Objects That Allow for Values of Different Types](https://doc.rust-lang.org/book/ch17-02-trait-objects.html)
- [procedural Macros](https://doc.rust-lang.org/reference/procedural-macros.html)
